name: Bristilian
favicon: null
layout_spectrum: 0.00444
typography_spectrum: 0.2559001555200666
title: Bristilian
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080c0d'
    - '#77a6d2'
    - '#294e7b'
    - '#e6e6e4'
    - '#ae7b66'
  brandStrength: 0.13989392295479774
  lightness: 0.32843984314240515
  saturation: 0.4436055913101882
  rhythmicContrast: 0.058614017674699426
purpose: []
